
name: 'kaiana'
version: '0.1'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
 This is a artwork package for Kaiana

grade: 'stable'
confinement: 'strict'

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
